package api.fuzzy;
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_Fuzzy_IAr_P_Comentario                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "P_Comentario"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//



public class TP_Fuzzy_IAr_P_Comentario {
 private double min = 0.0;
 private double max = 1.0;
 private double step = 0.00392156862745098;
 double _ps_Bajo[] = { 0.0,0.25,0.5 };
 double _pl_Bajo[] = {  };
 double _ps_Medio[] = { 0.25,0.5,0.75 };
 double _pl_Medio[] = {  };
 double _ps_Alto[] = { 0.5,0.75,1.0 };
 double _pl_Alto[] = {  };
 MF_xfl_triangle Bajo = new MF_xfl_triangle(min,max,step,_ps_Bajo,_pl_Bajo);
 MF_xfl_triangle Medio = new MF_xfl_triangle(min,max,step,_ps_Medio,_pl_Medio);
 MF_xfl_triangle Alto = new MF_xfl_triangle(min,max,step,_ps_Alto,_pl_Alto);
}


