package api.fuzzy;

//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_Fuzzy_IAr_Vejez                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "Vejez"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//



public class TP_Fuzzy_IAr_Vejez {
 private double min = 1935.0;
 private double max = 2015.0;
 private double step = 0.3137254901960784;
 double _ps_Muy_Vieja[] = { 1915.0,1935.0,1955.0,1975.0 };
 double _pl_Muy_Vieja[] = {  };
 double _ps_Vieja[] = { 1955.0,1975.0,1995.0 };
 double _pl_Vieja[] = {  };
 double _ps_Actual[] = { 1975.0,1995.0,2015.0,2035.0 };
 double _pl_Actual[] = {  };
 MF_xfl_trapezoid Muy_Vieja = new MF_xfl_trapezoid(min,max,step,_ps_Muy_Vieja,_pl_Muy_Vieja);
 MF_xfl_triangle Vieja = new MF_xfl_triangle(min,max,step,_ps_Vieja,_pl_Vieja);
 MF_xfl_trapezoid Actual = new MF_xfl_trapezoid(min,max,step,_ps_Actual,_pl_Actual);
}


