package api.fuzzy;
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_Fuzzy_IAr_Recomendada                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: Type "Recomendada"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//



public class TP_Fuzzy_IAr_Recomendada {
 private double min = 0.0;
 private double max = 100.0;
 private double step = 0.39215686274509803;
 double _ps_Poco_recomendada[] = { -30.0,0.0,40.0 };
 double _pl_Poco_recomendada[] = {  };
 double _ps_Medianamente_recomendada[] = { 25.0,50.0,75.0 };
 double _pl_Medianamente_recomendada[] = {  };
 double _ps_Muy_Recomendada[] = { 60.0,100.0,150.0 };
 double _pl_Muy_Recomendada[] = {  };
 MF_xfl_triangle Poco_recomendada = new MF_xfl_triangle(min,max,step,_ps_Poco_recomendada,_pl_Poco_recomendada);
 MF_xfl_triangle Medianamente_recomendada = new MF_xfl_triangle(min,max,step,_ps_Medianamente_recomendada,_pl_Medianamente_recomendada);
 MF_xfl_triangle Muy_Recomendada = new MF_xfl_triangle(min,max,step,_ps_Muy_Recomendada,_pl_Muy_Recomendada);
}


